-- Seed completo de 111 produtos para Forneiro Éden
-- Execute no SQL Editor do Supabase

INSERT INTO public.products (id, name, data, created_at) VALUES
-- COMBOS (2)
('combo-casal', 'Pizza Combo Casal', '{"price":63.99,"description":"1 pizza grande (sabores promocionais) + Borda requeijão grátis + Refrigerante 2L","category":"combos","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('combo-familia', 'Combo Família', '{"price":114.99,"description":"2 pizzas grandes (sabores promocionais) + Borda requeijão grátis + Refrigerante 2L","category":"combos","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),

-- PROMOCIONAIS (10)
('promo-alema', 'Alemã', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Pizza leve e refrescante","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('promo-argentina', 'Argentina', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Combinação clássica e saborosa","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('promo-bauru', 'Bauru', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Clássica e saudável","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('promo-calab-acebol', 'Calab. Acebol', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Para quem gosta de calabresa tradicional","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('promo-calacatu', 'Calacatu', '{"priceSmall":43.99,"priceLarge":55.99,"description":"Calabresa com catupiry premium","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('promo-italiana', 'Italiana', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Leve e refrescante","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('promo-milho-mussa', 'Milho e Mussa', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Vegetariana e deliciosa","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('promo-presunto-catu', 'Presunto Catu', '{"priceSmall":43.99,"priceLarge":55.99,"description":"Presunto com catupiry premium","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('promo-romeu-julieta', 'Romeu e Julieta', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Clássica brasileira, doce e salgada","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('promo-seleta', 'Seléta', '{"priceSmall":43.99,"priceLarge":43.99,"description":"Vegetariana completa","category":"promocionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),

-- TRADICIONAIS (27)
('trad-atum', 'Atum', '{"priceSmall":60.99,"priceLarge":60.99,"description":"Deliciosa e nutritiva","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-americana', 'Americana', '{"priceSmall":58.99,"priceLarge":58.99,"description":"Clássica mundial","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-alho-oleo', 'Alho e Óleo', '{"priceSmall":52.99,"priceLarge":52.99,"description":"Simples e saborosa","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-bacon', 'Bacon', '{"priceSmall":60.99,"priceLarge":60.99,"description":"Para fãs de bacon","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-baiana', 'Baiana', '{"priceSmall":54.99,"priceLarge":54.99,"description":"Autêntica baiana com pimenta","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-brocolis', 'Brócolis', '{"priceSmall":67.99,"priceLarge":67.99,"description":"Completa e saudável","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-calab-mussa', 'Calab e Mussa', '{"priceSmall":50.99,"priceLarge":50.99,"description":"Tradicional pura","category":"tradicionais","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-champignon', 'Champignon', '{"priceSmall":54.99,"priceLarge":54.99,"description":"Vegetariana sofisticada","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-dois-queijos', 'Dois Queijos', '{"priceSmall":51.99,"priceLarge":62.99,"description":"Queijuda deliciosa","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-frango-mussa', 'Frango e Mussa', '{"priceSmall":57.99,"priceLarge":57.99,"description":"Leve e saborosa","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-frango-catupiry', 'Frango e Catupi', '{"priceSmall":57.99,"priceLarge":69.99,"description":"Premium acessível","category":"tradicionais","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-francesa', 'Francesa', '{"priceSmall":65.99,"priceLarge":65.99,"description":"Sofisticada clássica","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-lombinho', 'Lombinho', '{"priceSmall":55.99,"priceLarge":55.99,"description":"Saudável e nobre","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-marguerita', 'Marguerita', '{"priceSmall":51.99,"priceLarge":51.99,"description":"Italiana autêntica","category":"tradicionais","is_popular":true,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-marguerita-alho', 'Marguerita Alho e Óleo', '{"priceSmall":55.99,"priceLarge":55.99,"description":"Margherita reforçada","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-mussarela', 'Mussarela', '{"priceSmall":51.99,"priceLarge":51.99,"description":"A mais clássica de todas","category":"tradicionais","is_popular":true,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-milho-catupiry', 'Milho com Catupiry', '{"priceSmall":51.99,"priceLarge":62.99,"description":"Doce e salgada","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-napolitana', 'Napolitana', '{"priceSmall":52.99,"priceLarge":52.99,"description":"Italiana simples","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-palmito', 'Palmito', '{"priceSmall":53.99,"priceLarge":53.99,"description":"Vegetariana sofisticada","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-portuguesa', 'Portuguesa', '{"priceSmall":56.99,"priceLarge":56.99,"description":"A mais completa","category":"tradicionais","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-quatro-queijos', 'Quatro Queijos Trad', '{"priceSmall":61.99,"priceLarge":73.99,"description":"Para apreciadores de queijo","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-toscana', 'Toscana', '{"priceSmall":50.99,"priceLarge":50.99,"description":"Italiana com calabresa","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-tres-queijos', 'Três Queijos', '{"priceSmall":57.99,"priceLarge":69.99,"description":"Triologia de queijos","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-siciliana', 'Siciliana', '{"priceSmall":60.99,"priceLarge":60.99,"description":"Italiana robusta","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-vegetariana', 'Vegetariana Trad', '{"priceSmall":65.99,"priceLarge":65.99,"description":"Vegetariana completa","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('trad-frango-cheddar', 'Frango e Cheddar', '{"priceSmall":66.99,"priceLarge":66.99,"description":"Cremosa e saborosa","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('trad-brasileira', 'Brasileira', '{"priceSmall":69.99,"priceLarge":81.99,"description":"Premium com cara de Brasil","category":"tradicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),

-- PREMIUM (14)
('prem-carijo', 'Carijo', '{"priceSmall":65.99,"priceLarge":77.99,"description":"Combinação perfeita com texturas variadas","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-cinco-queijos', 'Cinco Queijos', '{"priceSmall":66.99,"priceLarge":78.99,"description":"Para os amantes de queijo - cinco queijos nobres","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('prem-frango-forneiro', 'Frango Forneiro', '{"priceSmall":69.99,"priceLarge":81.99,"description":"Receita especial da casa","category":"premium","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-frango-catu-bacon', 'Frango Catupiry com Bacon', '{"priceSmall":67.99,"priceLarge":79.99,"description":"Combinação de sabores únicos","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-grega', 'Grega', '{"priceSmall":69.99,"priceLarge":81.99,"description":"Refinada e sofisticada","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-moda-carlinhos', 'Moda do Carlinhos', '{"priceSmall":84.99,"priceLarge":96.99,"description":"Premium completa com múltiplos ingredientes","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-moda-casa', 'Moda da Casa', '{"priceSmall":69.99,"priceLarge":81.99,"description":"Receita clássica da pizzaria","category":"premium","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-moda-cliente', 'Moda do Cliente', '{"priceSmall":71.99,"priceLarge":79.99,"description":"Customize sua própria pizza premium - escolha até 6 ingredientes grátis","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":true}', NOW()),
('prem-moda-chefe', 'Moda do Chefe', '{"priceSmall":85.99,"priceLarge":96.99,"description":"Criação exclusiva do chef","category":"premium","is_popular":false,"is_new":true,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-moda-patrao', 'Moda do Patrão', '{"priceSmall":65.99,"priceLarge":77.99,"description":"Premium robusta e saborosa","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-portuguesa-forn', 'Portuguesa Forn', '{"priceSmall":46.99,"priceLarge":65.99,"description":"Versão premium da portuguesa tradicional","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-pepperoni', 'Pepperoni', '{"priceSmall":69.99,"priceLarge":76.99,"description":"Clássica internacional com toque especial","category":"premium","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('prem-primavera-catu', 'Primavera com Catupiry', '{"priceSmall":69.99,"priceLarge":81.99,"description":"Fresca e sofisticada","category":"premium","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),

-- ESPECIAIS (16)
('esp-carne-seca', 'Carne Seca', '{"priceSmall":55.99,"priceLarge":73.99,"description":"Sabor nordestino marcante","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-carne-seca-catu', 'Carne Seca com Catupiry', '{"priceSmall":60.99,"priceLarge":82.99,"description":"Nordestina cremosa","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-costela', 'Costela', '{"priceSmall":55.99,"priceLarge":71.99,"description":"Carne de qualidade","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-costela-catu', 'Costela com Catupiry', '{"priceSmall":60.99,"priceLarge":82.99,"description":"Costela premium","category":"especiais","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-frango-cream', 'Frango com Cream Cheese', '{"priceSmall":50.99,"priceLarge":68.99,"description":"Cremosa e saborosa","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-lombo-especial', 'Lombo Especial', '{"priceSmall":47.99,"priceLarge":70.99,"description":"Saudável e nobre","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-lombo-cream', 'Lombo com Cream Cheese', '{"priceSmall":47.99,"priceLarge":70.99,"description":"Proteína pura","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-light', 'Light', '{"priceSmall":47.99,"priceLarge":70.99,"description":"Para quem cuida da saúde","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-modesta', 'Modesta', '{"priceSmall":47.99,"priceLarge":70.99,"description":"Leve e cremosa","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-palmito-especial', 'Palmito Especial', '{"priceSmall":50.99,"priceLarge":70.99,"description":"Vegetariana sofisticada","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('esp-peru', 'Peru', '{"priceSmall":43.99,"priceLarge":57.99,"description":"Saudável e leve","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-sorocabana', 'Sorocabana', '{"priceSmall":52.99,"priceLarge":75.99,"description":"Completa e equilibrada","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-strogonoff', 'Strogonoff de Frango', '{"priceSmall":50.99,"priceLarge":72.99,"description":"Cremosa e rica","category":"especiais","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-suina', 'Suína', '{"priceSmall":47.99,"priceLarge":70.99,"description":"Para fãs de carne suína","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-sulamericana', 'Sulamericana', '{"priceSmall":52.99,"priceLarge":75.99,"description":"Saborosa e encorpada","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('esp-vegetariana-esp', 'Vegetariana Especial', '{"priceSmall":52.99,"priceLarge":75.99,"description":"Vegetariana premium completa","category":"especiais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),

-- DOCES (7)
('doce-brigadeiro', 'Brigadeiro', '{"priceSmall":40.99,"priceLarge":52.99,"description":"Tradicional brasileira, doce e irresistível","category":"doces","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('doce-californa', 'Califórnia', '{"priceSmall":40.99,"priceLarge":52.99,"description":"Refrescante e tropical","category":"doces","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('doce-chocolate-morango', 'Chocolate com Morango', '{"priceSmall":48.99,"priceLarge":65.99,"description":"Sofisticada e romântica","category":"doces","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('doce-chocomix', 'Chocomix', '{"priceSmall":45.99,"priceLarge":58.99,"description":"Dualidade de sabores","category":"doces","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('doce-doce-leite', 'Doce de Leite', '{"priceSmall":45.99,"priceLarge":55.99,"description":"Doçura concentrada","category":"doces","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('doce-ovomaltine', 'Ovomaltine', '{"priceSmall":45.99,"priceLarge":62.99,"description":"Cremosa e sofisticada","category":"doces","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('doce-oreo', 'Oreo', '{"priceSmall":48.99,"priceLarge":63.99,"description":"Requintada e moderna","category":"doces","is_popular":false,"is_new":true,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),

-- BEBIDAS (3)
('beb-coca-2l', 'Coca-Cola 2L', '{"price":14.00,"description":"Refrigerante gelado refrescante","category":"bebidas","is_popular":true,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('beb-guarana-2l', 'Guaraná Antarctica 2L', '{"price":14.00,"description":"Refrigerante de guaraná gelado","category":"bebidas","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('beb-sprite-2l', 'Sprite 2L', '{"price":14.00,"description":"Refrigerante cítrico gelado","category":"bebidas","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),

-- ADICIONAIS (23)
('add-alho', 'Alho Gratinado', '{"price":6.99,"description":"Alho extra gratinado","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-cebola', 'Cebola', '{"price":6.99,"description":"Cebola fresca extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-ervilha', 'Ervilha', '{"price":6.99,"description":"Ervilha fresca extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-milho', 'Milho', '{"price":6.99,"description":"Milho fresco extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-pimenta', 'Pimenta', '{"price":6.99,"description":"Pimenta fresca extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-ovo', 'Ovo', '{"price":8.99,"description":"Ovo fresco extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-atum', 'Atum', '{"price":13.99,"description":"Atum original extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('add-bacon', 'Bacon', '{"price":14.99,"description":"Bacon crocante extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('add-frango', 'Frango', '{"price":12.99,"description":"Frango desfiado extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('add-lombinho', 'Lombinho', '{"price":12.99,"description":"Lombo canadense extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('add-palmito', 'Palmito', '{"price":12.99,"description":"Palmito fresco extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-pepperoni', 'Pepperoni', '{"price":14.99,"description":"Pepperoni extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('add-presunto', 'Presunto', '{"price":13.99,"description":"Presunto premium extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":false,"is_active":true,"is_customizable":false}', NOW()),
('add-batata-palha', 'Batata Palha', '{"price":9.99,"description":"Batata palha crocante extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-brocolis', 'Brócolis', '{"price":13.99,"description":"Brócolis fresco extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-champignon', 'Champignon', '{"price":10.99,"description":"Champignon fresco extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-provolone', 'Provolone', '{"price":9.99,"description":"Queijo provolone extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-catupiry-dallora', 'Catupiry Dallora', '{"price":8.99,"description":"Catupiry marca Dallora extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-catupiry-scala', 'Catupiry Scala', '{"price":13.99,"description":"Catupiry scala ou origin extra (premium)","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-cheddar', 'Cheddar Scala', '{"price":13.99,"description":"Cheddar scala extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-gorgonzola', 'Gorgonzola', '{"price":12.99,"description":"Queijo gorgonzola azul extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-mussarela', 'Mussarela', '{"price":13.99,"description":"Mussarela extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('add-parmesao', 'Parmesão', '{"price":12.99,"description":"Queijo parmesão ralado extra","category":"adicionais","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),

-- BORDAS (9)
('borda-requeijao', 'Requeijão', '{"price":6.99,"description":"Borda recheada com requeijão, clássica e cremosa","category":"bordas","is_popular":true,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-mussarela', 'Mussarela', '{"price":20.99,"description":"Borda recheada com mussarela derretida, generosa","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-cheddar', 'Cheddar Scala', '{"price":17.99,"description":"Borda recheada com cheddar scala, cremosa e saborosa","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-catupiry', 'Catupiry Scala', '{"price":17.99,"description":"Borda recheada com catupiry scala, macio e delicioso","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-cream-cheese', 'Cream Cheese', '{"price":17.99,"description":"Borda recheada com cream cheese scala, sofisticada","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-chocolate-preto', 'Chocolate Preto', '{"price":17.99,"description":"Borda recheada com chocolate preto","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-chocolate-branco', 'Chocolate Branco', '{"price":17.99,"description":"Borda recheada com chocolate branco, mais doce","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-doce-leite', 'Doce de Leite', '{"price":17.99,"description":"Borda recheada com doce de leite, tradicional","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW()),
('borda-goiabada', 'Goiabada', '{"price":17.99,"description":"Borda recheada com goiabada, sabor tropical","category":"bordas","is_popular":false,"is_new":false,"is_vegetarian":true,"is_active":true,"is_customizable":false}', NOW())

ON CONFLICT(id) DO UPDATE SET 
  name = EXCLUDED.name,
  data = EXCLUDED.data;
